export const SIDE_NAV_MENU_ACTION_TYPES = {
    FETCH_SIDE_NAV_MENU_START: 'side-nav-menu/FETCH_SIDE_NAV_MENU_START',
    FETCH_SIDE_NAV_MENU_SUCCESS: 'side-nav-menu/FETCH_SIDE_NAV_MENU_SUCCESS',
    FETCH_SIDE_NAV_MENU_FAILED: 'side-nav-menu/FETCH_SIDE_NAV_MENU_FAILED'
  };
  