export const QUIZ_ACTION_TYPES = {
  UPDATE_ANSWER: 'quiz/UPDATE_ANSWER',
  START_QUIZ_COUNTDOWN: 'quiz/START_QUIZ_COUNTDOWN',
  RESET_QUIZ_COUNTDOWN: 'quiz/RESET_QUIZ_COUNTDOWN',
  SUBMIT_QUIZ: 'quiz/SUBMIT_QUIZ'
};
