export const COURSES_ACTION_TYPES = {
  FETCH_COURSES_START: 'course/FETCH_COURSES_START',
  FETCH_COURSES_SUCCESS: 'course/FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILED: 'course/FETCH_COURSES_FAILED',
};
